### ISSUE TITLE
RINEX file v2.11 for PPP generation fails

### ISSUE THREAD

**Issue by hcwinsemius** [Stefal/rtkbase#102]
This sounds like a near-ideal functionality for easy PPP. But unfortunately there seems to be a bug in it.

I get the following HTML formatted error on screen:

**Failed!**

End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of 2020-08-28_18-52-20_GNSS-1.ubx or 2020-08-28_18-52-20_GNSS-1.ubx.zip, and cannot find 2020-08-28_18-52-20_GNSS-1.ubx.ZIP, period. End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of 2020-08-28_18-52-20_GNSS-1.ubx or 2020-08-28_18-52-20_GNSS-1.ubx.zip, and cannot find 2020-08-28_18-52-20_GNSS-1.ubx.ZIP, period. rm: cannot remove '': No such file or directory

**Comment by Stefal** [comment]
Hi!
The Rinex conversion script need a zip file as input, and you try to convert a ubx file.
The actual conversion script is a quick and dirty one. Building a complete Rinex conversion tool is on my todo.

**Comment by hcwinsemius** [comment]
Good to know. Should I somehow zip the ubx file then? I am not fully in the code base yet although I may dig into it. 

If you have an example how to get the rinex output from the front end I'd love to try it.

**Comment by Stefal** [comment]
Every day, the ubx file from the previous day is zipped. Is it not the behaviour you see?
