### ISSUE TITLE
archive_and_clean.sh is deleting files if less than 5G available space

### ISSUE THREAD

**Issue by steveb2014** [Stefal/rtkbase#132]
**Describe the bug**
I am on a RASPI4 with a small SSD and noticed that archive_and_clean.sh was deleting all of my files each time it ran.  Turns out that the comment in the code and the code itself differ.  The comment says it should delete if < 500M available with it was coded as < 5G.  I believe the comment defines the correct behavior and the code has an extra zero by accident.

**Code says:
   #Check if there is enough available space (more than 500MB), and delete oldest archive if needed.

> while [[ $(check_space) -lt 5000000 ]]
   do

**Code should say:
   #Check if there is enough available space (more than 500MB), and delete oldest archive if needed.

> while [[ $(check_space) -lt 500000 ]]
   do

**Comment by Stefal** [comment]
Hi @steveb2014!

Good catch!
Thank you for this bug report, it will be fixed in the next release.
