### ISSUE TITLE
At README.md step 4, the file: 'pystemd-0.8.1590398158-cp37-cp37m-linux_armv7l.whl' is missing 

### ISSUE THREAD

**Issue by vakhus** [Stefal/rtkbase#138]
**Describe the bug**
At step 4 of manual installation, as in README.md:
`python3 -m pip install rtkbase/tools/pystemd-0.8.1590398158-cp37-cp37m-linux_armv7l.whl`
 the file pystemd-0.8.1590398158-cp37-cp37m-linux_armv7l.whl,
is missing from the directory rtkbase/tools/

Raspberry pi 4 Raspbian GNU/Linux 10 (buster)

**Comment by Stefal** [comment]
It's not needed anymore.
Thank you for this report.
