### ISSUE TITLE
enable chrony fails

### ISSUE THREAD

**Issue by vakhus** [Stefal/rtkbase#139]
At step 6 of Readme.md:
`sudo ./install.sh --gpsd-chrony`
I get:
`...   
Executing: /lib/systemd/systemd-sysv-install enable chrony
Failed to enable unit: File /etc/systemd/system/chronyd.service already exists and is a symlink to /lib/systemd/system/chrony.service.`

**Software/Hardware (please complete the following information):**
Raspberry pi 4 Raspbian GNU/Linux 10 (buster)
Arduisimple simpleRTK2B
Antenna: AS-ANT2B-CAL

**Comment by Stefal** [comment]
Hi!
I get this error too, but chrony works despite this message.
