### ISSUE TITLE
system informations

### ISSUE THREAD

**Issue by buched** [Stefal/rtkbase#144]
a new tab maybe named system monitor with some information about cpu temp, space used, ...

**Comment by Stefal** [comment]
What do you think about this?

![image](https://user-images.githubusercontent.com/8255984/118255919-20f1ee00-b4ad-11eb-98ce-f997a86014fa.png)

It's on the settings webpage. When there will be too much informations I will create another tab.

**Comment by buched** [comment]
ParfaitMerciLe 14 mai 2021 12:10, Stefal ***@***.***> a écrit :
What do you think about this?

It's on the settings webpage. When there will be too much informations I will create another tab.

**Comment by Stefal** [comment]
fixed in https://github.com/Stefal/rtkbase/releases/tag/2.3.0
