### ISSUE TITLE
'INSTALLING RTKBASE REQUIREMENTS' psutil install failiure on fresh PiOS

### ISSUE THREAD

**Issue by electroklas** [Stefal/rtkbase#165]
newbi, 
Tried to install 2.3.0 on a fresh PiOs (2021-05-07 RaspberryPi Desctop, on a RPi3)
and got stuck on RTKBASE REQUIREMENTS installation process:

_Installing collected packages: psutil, Flask-WTF, Flask-SocketIO, Flask-Login, eventlet, Bootstrap-Flask
  Attempting uninstall: psutil
    Found existing installation: psutil 5.5.1
ERROR: Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall._

And the installer exited after that

Any tips for a linux /phyton noob...

**Comment by Stefal** [comment]
Thank you for this report.

Most users install the RpiOs lite which include less packages. Inside RpiOs desktop, there is an already existing old `psutil` release which can't be upgraded with `pip`.

As a workaround, you can try this `sudo apt remove python3-psutil` then restart the RTKBase installation.

**Comment by electroklas** [comment]
Thanks, that solved my issues….

I should of course selected the lite version for this appoication, but i guess that i had a stroke of bad luck when selecting image.. ;)
