### ISSUE TITLE
Version de rtkbase

### ISSUE THREAD

**Issue by badaboom** [Stefal/rtkbase#174]
**
Dans centipede.fr ,la cartographie des bases,quand on clique sur une base, on a le numéro de la version de ublox mais pas celle de rtkbase. 

Oups c'est déjà le cas mais c'est confu

**Comment by badaboom** [comment]
Ça n'a pas suivi mon commentaire.. dans centipede.fr, la fiche de la base on a la version de ublox mais pas celle de rtkbase.

Exemple SGc , ublox 2.20 il manquerait rtkbase 2.31

**Comment by Stefal** [comment]
Bonjour,

Si c'est la présentation sur centipede.fr qui nécessite des améliorations, alors je ne peux pas faire grand chose. C'est plutôt sur le dépot centipede qu'il faut créer un ticket : https://github.com/jancelin/centipede
