### ISSUE TITLE
Satellite status not working, ardusimple F9P

### ISSUE THREAD

**Issue by sytem** [Stefal/rtkbase#177]
**Describe the bug**
Lost satellite status and map display on web gui. 

**To Reproduce**
Installed fresh image ( at first I was replacing corrupt sd-card, but happen also with another RPi + ardusimple that has worked before with older version) No data shown, but sending to rtk2go seems to be ok.

Have tried to reconfigure receiver with command ./tools/install.sh --detect-usb-gnss --configure-gnss

**Expected behavior**
See satellite status bar and map again

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.3.1
 - OS: from https://github.com/jancelin/pi-gen_RTKbase/releases/tag/BaseGNSS-RPi-2.3.1 
 - SBC: Raspberry Pi 3B+
 - GNSS Device: Ardusimple Ublox_ZED-F9P
 - Connection type: USB

**Comment by Stefal** [comment]
I just did a fresh install on a Pi 3B+ with a resetted F9P. Everything is fine.

Which port is in use on your Pi ? Mine is ttyACM0.

btw: on the map, do you see the entire world, or nothing at all ?

**Comment by sytem** [comment]
![Screen Shot 2021-09-16 at 20 08 44](https://user-images.githubusercontent.com/10594837/133655499-576829ee-4f58-4a65-9a85-f5e3d2a25dc5.png)

Completly empty interface. At the same time http://rtk2go.com:2101/SNIP::MOUNTPT?NAME=koivumaeki where this instance is sending, seems to be ok

ttyACM0 in use, as is was before corrupted SD and reinstall to new card.

Could there be some setting in F9P that is not resetting correctly with install script?

Diagnostic is showing lot of repeating message, I think I increased log level when I was looking if there is any data.

str2str_tcp.service : Active
● str2str_tcp.service - RTKBase Tcp
Loaded: loaded (/etc/systemd/system/str2str_tcp.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2021-09-15 10:18:03 CEST; 1 day 8h ago
Process: 525 ExecStart=/home/basegnss/rtkbase/run_cast.sh in_serial out_tcp (code=exited, status=0/SUCCESS)
Main PID: 557 (str2str)
Tasks: 2 (limit: 2063)
CGroup: /system.slice/str2str_tcp.service
└─557 /usr/local/bin/str2str -in serial://ttyACM0:115200:8:n:1#ubx -out tcpsvr://:5015 -t 3 -fl /home/basegnss/rtkbase/logs/str2str_tcp.log

Sep 16 19:08:52 basegnss run_cast.sh[525]: 2021/09/16 17:09:11 [CC---] 598553400 B 39480 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:09:47 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_tcp.service
Sep 16 19:09:47 basegnss run_cast.sh[525]: 2021/09/16 17:10:06 [CC---] 598834104 B 39226 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:09:52 basegnss run_cast.sh[525]: 2021/09/16 17:10:11 [CC---] 598860316 B 39344 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:10:47 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_tcp.service
Sep 16 19:10:47 basegnss run_cast.sh[525]: 2021/09/16 17:11:06 [CC---] 599145108 B 39477 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:10:52 basegnss run_cast.sh[525]: 2021/09/16 17:11:11 [CC---] 599171260 B 39162 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:11:47 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_tcp.service
Sep 16 19:11:47 basegnss run_cast.sh[525]: 2021/09/16 17:12:06 [CC---] 599456124 B 39336 bps (0) /dev/ttyACM0 (1) 3 clients
Sep 16 19:11:52 basegnss run_cast.sh[525]: 2021/09/16 17:12:11 [CC---] 599482244 B 39169 bps (0) /dev/ttyACM0 (1) 3 clients

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
Sep 15 10:18:03 basegnss systemd[1]: Starting RTKBase Tcp...
Sep 15 10:18:03 basegnss run_cast.sh[525]: stream server start
Sep 15 10:18:03 basegnss systemd[1]: Started RTKBase Tcp.
Sep 15 10:18:03 basegnss run_cast.sh[525]: 2021/09/15 08:18:22 [CC---] 0 B 0 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Sep 15 10:44:26 basegnss systemd-journald[143]: Suppressed 11 messages from str2str_tcp.service
Sep 15 10:44:26 basegnss run_cast.sh[525]: 2021/09/15 08:44:45 [CC---] 264880 B 36826 bps (0) /dev/ttyACM0 (1) 4 clients
Sep 15 10:44:31 basegnss run_cast.sh[525]: 2021/09/15 08:44:50 [CC---] 287180 B 37965 bps (0) /dev/ttyACM0 (1) 4 clients
Sep 15 10:45:26 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_tcp.service
Sep 15 10:45:26 basegnss run_cast.sh[525]: 2021/09/15 08:45:45 [CC---] 558856 B 40363 bps (0) /dev/ttyACM0 (1) 4 clients
Sep 15 10:45:31 basegnss run_cast.sh[525]: 2021/09/15 08:45:50 [CC---] 582840 B 40673 bps (0) /dev/ttyACM0 (1) 4 clients

thousands of similar lines removed...

Sep 16 19:10:37 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_local_ntrip_caster.service
Sep 16 19:10:37 basegnss run_cast.sh[547]: 2021/09/16 17:10:56 [CW---] 599093396 B 39152 bps (0) 127.0.0.1 (1) waiting...
Sep 16 19:10:42 basegnss run_cast.sh[547]: 2021/09/16 17:11:01 [CW---] 599119500 B 39015 bps (0) 127.0.0.1 (1) waiting...
Sep 16 19:11:37 basegnss systemd-journald[143]: Suppressed 10 messages from str2str_local_ntrip_caster.service
Sep 16 19:11:37 basegnss run_cast.sh[547]: 2021/09/16 17:11:56 [CW---] 599404608 B 40618 bps (0) 127.0.0.1 (1) waiting...
Sep 16 19:11:42 basegnss run_cast.sh[547]: 2021/09/16 17:12:01 [CW---] 599430696 B 39184 bps (0) 127.0.0.1 (1) waiting...

str2str_rtcm_svr.service : Inactive
● str2str_rtcm_svr.service - RTKBase rtcm server
Loaded: loaded (/etc/systemd/system/str2str_rtcm_svr.service; disabled; vendor preset: enabled)
Active: inactive (dead)

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
-- No entries --

str2str_rtcm_serial.service : Inactive
● str2str_rtcm_serial.service - RTKBase serial rtcm output
Loaded: loaded (/etc/systemd/system/str2str_rtcm_serial.service; disabled; vendor preset: enabled)
Active: inactive (dead)

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
-- No entries --

str2str_file.service : Inactive
● str2str_file.service - RTKBase File - Log data
Loaded: loaded (/etc/systemd/system/str2str_file.service; disabled; vendor preset: enabled)
Active: inactive (dead) since Thu 2021-09-16 12:44:35 CEST; 6h ago
Process: 562 ExecStart=/home/basegnss/rtkbase/run_cast.sh in_tcp out_file (code=exited, status=0/SUCCESS)
Main PID: 882 (code=exited, status=0/SUCCESS)

Sep 15 10:18:03 basegnss systemd[1]: Starting RTKBase File - Log data...
Sep 15 10:43:38 basegnss systemd[1]: Started RTKBase File - Log data.
Sep 16 12:44:34 basegnss systemd[1]: Stopping RTKBase File - Log data...
Sep 16 12:44:35 basegnss systemd[1]: str2str_file.service: Succeeded.
Sep 16 12:44:35 basegnss systemd[1]: Stopped RTKBase File - Log data.

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
Sep 15 10:18:03 basegnss systemd[1]: Starting RTKBase File - Log data...
Sep 15 10:43:38 basegnss systemd[1]: Started RTKBase File - Log data.
Sep 16 12:44:34 basegnss systemd[1]: Stopping RTKBase File - Log data...
Sep 16 12:44:35 basegnss systemd[1]: str2str_file.service: Succeeded.
Sep 16 12:44:35 basegnss systemd[1]: Stopped RTKBase File - Log data.

rtkbase_archive.timer : Active
● rtkbase_archive.timer - Run rtkbase_archive.service everyday at 04H00
Loaded: loaded (/etc/systemd/system/rtkbase_archive.timer; enabled; vendor preset: enabled)
Active: active (waiting) since Wed 2021-09-15 10:18:02 CEST; 1 day 8h ago
Trigger: Fri 2021-09-17 04:00:00 CEST; 8h left

Sep 15 10:18:02 basegnss systemd[1]: Started Run rtkbase_archive.service everyday at 04H00.

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
Sep 15 10:18:02 basegnss systemd[1]: Started Run rtkbase_archive.service everyday at 04H00.

rtkbase_archive.service : Inactive
● rtkbase_archive.service - RTKBase - Archiving and cleaning raw data
Loaded: loaded (/etc/systemd/system/rtkbase_archive.service; static; vendor preset: enabled)
Active: inactive (dead) since Thu 2021-09-16 04:02:04 CEST; 15h ago
Process: 5485 ExecStart=/home/basegnss/rtkbase/archive_and_clean.sh (code=exited, status=0/SUCCESS)
Main PID: 5485 (code=exited, status=0/SUCCESS)

Sep 16 04:00:19 basegnss systemd[1]: Starting RTKBase - Archiving and cleaning raw data...
Sep 16 04:00:20 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_08-43-56_GNSS-1.ubx.tag (deflated 39%)
Sep 16 04:01:23 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_08-43-56_GNSS-1.ubx (deflated 59%)
Sep 16 04:02:03 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_00-00-00_GNSS-1.ubx (deflated 59%)
Sep 16 04:02:04 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_00-00-00_GNSS-1.ubx.tag (deflated 39%)
Sep 16 04:02:04 basegnss systemd[1]: rtkbase_archive.service: Succeeded.
Sep 16 04:02:04 basegnss systemd[1]: Started RTKBase - Archiving and cleaning raw data.

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
Sep 16 04:00:19 basegnss systemd[1]: Starting RTKBase - Archiving and cleaning raw data...
Sep 16 04:00:20 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_08-43-56_GNSS-1.ubx.tag (deflated 39%)
Sep 16 04:01:23 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_08-43-56_GNSS-1.ubx (deflated 59%)
Sep 16 04:02:03 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_00-00-00_GNSS-1.ubx (deflated 59%)
Sep 16 04:02:04 basegnss archive_and_clean.sh[5485]: adding: 2021-09-15_00-00-00_GNSS-1.ubx.tag (deflated 39%)
Sep 16 04:02:04 basegnss systemd[1]: rtkbase_archive.service: Succeeded.
Sep 16 04:02:04 basegnss systemd[1]: Started RTKBase - Archiving and cleaning raw data.

rtkbase_web.service : Active
● rtkbase_web.service - RTKBase Web Server
Loaded: loaded (/etc/systemd/system/rtkbase_web.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2021-09-15 10:18:03 CEST; 1 day 8h ago
Main PID: 556 (python3)
Tasks: 2 (limit: 2063)
CGroup: /system.slice/rtkbase_web.service
├─ 556 /usr/bin/python3 /home/basegnss/rtkbase/web_app/server.py
└─9698 systemctl status rtkbase_web.service

Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...

-- Logs begin at Wed 2021-09-15 10:17:01 CEST, end at Thu 2021-09-16 19:11:52 CEST. --
Sep 15 10:18:03 basegnss systemd[1]: Started RTKBase Web Server.
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 1
Sep 16 19:09:47 basegnss python3[556]: /usr/local/bin
Sep 16 19:09:47 basegnss python3[556]: /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Getting a list of available logs
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22 Now loading the state printed above...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 7 Base mode launched
Sep 16 19:09:47 basegnss python3[556]: base state loaded
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: service status [{'service_unit': 'str2str_tcp.service', 'name': 'main', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_ntrip.service', 'name': 'ntrip', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_local_ntrip_caster.service', 'name': 'local_ntrip_caster', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_rtcm_svr.service', 'name': 'rtcm_svr', 'active': False, 'status': 'dead', 'result': 'success', 'state_ok': None}, {'service_unit': 'str2str_rtcm_serial.service', 'name': 'rtcm_serial', 'active': False, 'status': 'dead', 'result': 'success', 'state_ok': None}, {'service_unit': 'str2str_file.service', 'name': 'file', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'rtkbase_archive.timer', 'name': 'archive_timer', 'active': True, 'status': 'waiting'}, {'service_unit': 'rtkbase_archive.service', 'name': 'archive_service'}]
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 9a Attempting to launch rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: Launching rtkrcv with: "/usr/local/bin/rtkrcv -o /home/basegnss/rtkbase/web_app/rtklib_configs/rtkbase_ppp-static_default.conf"
Sep 16 19:09:47 basegnss python3[556]: rtkrcv launch successful
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 9b Attempting to start rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: rtkrcv start successful
Sep 16 19:09:47 basegnss python3[556]: Starting coordinate and satellite broadcast
Sep 16 19:09:47 basegnss python3[556]: Trying to stop rtkrcv
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10a Attempting to stop rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: rtkrcv stop successful
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10b Attempting to stop satellite broadcasting...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10c Attempting rtkrcv shutdown
Sep 16 19:09:47 basegnss python3[556]: rtkrcv shutdown successful
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Getting a list of available logs
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Received service to switch {'name': 'file', 'active': False}
Sep 16 19:09:47 basegnss python3[556]: Trying to stop service file
Sep 16 19:09:47 basegnss python3[556]: Received service to switch {'name': 'file', 'active': False}
Sep 16 19:09:47 basegnss python3[556]: Trying to stop service file
Sep 16 19:09:47 basegnss python3[556]: Received service to switch {'name': 'file', 'active': False}
Sep 16 19:09:47 basegnss python3[556]: Trying to stop service file
Sep 16 19:09:47 basegnss python3[556]: Received service to switch {'name': 'file', 'active': False}
Sep 16 19:09:47 basegnss python3[556]: Trying to stop service file
Sep 16 19:09:47 basegnss python3[556]: Received service to switch {'name': 'file', 'active': False}
Sep 16 19:09:47 basegnss python3[556]: Trying to stop service file
Sep 16 19:09:47 basegnss python3[556]: service status [{'service_unit': 'str2str_tcp.service', 'name': 'main', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_ntrip.service', 'name': 'ntrip', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_local_ntrip_caster.service', 'name': 'local_ntrip_caster', 'active': True, 'status': 'running', 'result': 'success', 'state_ok': True, 'btn_color': 'success', 'btn_off_color': 'outline-secondary'}, {'service_unit': 'str2str_rtcm_svr.service', 'name': 'rtcm_svr', 'active': False, 'status': 'dead', 'result': 'success', 'state_ok': None}, {'service_unit': 'str2str_rtcm_serial.service', 'name': 'rtcm_serial', 'active': False, 'status': 'dead', 'result': 'success', 'state_ok': None}, {'service_unit': 'str2str_file.service', 'name': 'file', 'active': False, 'status': 'dead', 'result': 'success', 'state_ok': None}, {'service_unit': 'rtkbase_archive.timer', 'name': 'archive_timer', 'active': True, 'status': 'waiting'}, {'service_unit': 'rtkbase_archive.service', 'name': 'archive_service'}]
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 9a Attempting to launch rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: Launching rtkrcv with: "/usr/local/bin/rtkrcv -o /home/basegnss/rtkbase/web_app/rtklib_configs/rtkbase_ppp-static_default.conf"
Sep 16 19:09:47 basegnss python3[556]: rtkrcv launch successful
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 9b Attempting to start rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: rtkrcv start successful
Sep 16 19:09:47 basegnss python3[556]: Starting coordinate and satellite broadcast
Sep 16 19:09:47 basegnss python3[556]: Trying to stop rtkrcv
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10a Attempting to stop rtkrcv...
Sep 16 19:09:47 basegnss python3[556]: rtkrcv stop successful
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10b Attempting to stop satellite broadcasting...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 10c Attempting rtkrcv shutdown
Sep 16 19:09:47 basegnss python3[556]: rtkrcv shutdown successful
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...
Sep 16 19:09:47 basegnss python3[556]: Could not find existing state, Launching default mode...
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 22a
Sep 16 19:09:47 basegnss python3[556]: Available configs to send:
Sep 16 19:09:47 basegnss python3[556]: []
Sep 16 19:09:47 basegnss python3[556]: Full state:
Sep 16 19:09:47 basegnss python3[556]: started : no
Sep 16 19:09:47 basegnss python3[556]: state : base
Sep 16 19:09:47 basegnss python3[556]: available_configs : []
Sep 16 19:09:47 basegnss python3[556]: system_time_correct : True
Sep 16 19:09:47 basegnss python3[556]: log_path : /home/basegnss/rtkbase/web_app/../data
Sep 16 19:09:47 basegnss python3[556]: Browser client disconnected
Sep 16 19:09:47 basegnss python3[556]: Browser client connected
Sep 16 19:09:47 basegnss python3[556]: RTKLIB 21 Trying to read previously saved state...

**Comment by Stefal** [comment]
Hmmm everything seems fine in the logs. It looks like your web browser doesn't load the status page correctly, because you should see the map, even without any GNSS receiver connected.
Could you try with another web browser, without any ad/js/... blocker ?

**Comment by sytem** [comment]
No difference between browsers: main firefox (yes, this has lot of blockers installed but nothing seems to be doing anything on these pages), Chrome and also Safari that is completly clean install. Same with another PC


Now when I looked web page with inspector, there are few JS errors:
![Screen Shot 2021-09-17 at 10 21 48](https://user-images.githubusercontent.com/10594837/133741576-9e0f3c1c-9337-4e91-b56c-efe1c170440a.png)

But as those files are minized, there is nothing for me to understand.

Map div is completly empty.

**Comment by sytem** [comment]
Now had time again to test this. with test instance, both local and vpn are working ok now (were also empty earlier, with no changes made. RPI was just unpowered for months) On production instance, I have only vpn access at the moment and there interface is empty.

Had to test production with local access next time I travell there

**Comment by sytem** [comment]
No difference in production unit with vpn or local ip

**Comment by biemond** [comment]
did we find out what it can be? , I have the same with ardusimple . all is fine except status.

also tried different browsers , operating system, ad blockers , in and outside iot network. nothing working.  
websockets gets data.

**Comment by biemond** [comment]
<img width="1355" alt="Screen Shot 2022-05-04 at 20 52 29" src="https://user-images.githubusercontent.com/1085004/166805717-5512c97e-1d5f-4dd0-9f71-5ee1f8cd30e5.png">

**Comment by Stefal** [comment]
@biemond 
Your problem seems different. Please open another issue.
