### ISSUE TITLE
Addition of PPS input to provide more precise clock?

### ISSUE THREAD

**Issue by XPav** [Stefal/rtkbase#178]
I see in /etc/chrony/chrony.conf that there's a commented out line for:

```#refclock PPS /dev/pps0 refid PPS lock GNSS```

Is there a list of thing that are needed to be done to allow for rtkbase to use the PPS, so that rtkbase can be a more accurate local time server (via NTP or PTP)?

**Comment by Stefal** [comment]
Hi!

Yes, there is a small guide to enable PPS in the readme : https://github.com/Stefal/rtkbase#other-usages

**Comment by XPav** [comment]
Hi!  Sorry, I didn't see that documentation.  Thanks very much!
