### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by mpena2099** [Stefal/rtkbase#181]
Hi. How are log files generated? On my list here I'm only seeing logs from a few days ago...

**Comment by mpena2099** [comment]
@Stefal , I did a fresh install using the "ready to flash Raspberry Pi release" and everything works OK, except the logs apparently.

There is nothing in /home/basegnss/rtkbase/logs ...

**Comment by Stefal** [comment]
Ho! Sorry, I thought you've asked for the raw gnss data.

With the default settings, there is no logfiles, except the systemd services logs. If you want some more logs, edit the `level=0` value inside `settings.conf`

**Comment by pterodyne** [comment]
This should be in the Wiki!  I just spent hours trying to find it.  Never occurred to me to look in the file service (even if it should have :)
