### ISSUE TITLE
RTK base send uBlox binary messages to rtk2go instead of RTCM

### ISSUE THREAD

**Issue by Leijoma** [Stefal/rtkbase#189]
I have an Ublox_ZED-F9P connected to a Raspberry PI with RTKBase. 
I have configured the F9P with the config tool and the cfg file that comes with RTKBase.
Everything looks good in the web interface and RTKBase sends data to rtk2Go, but it sends the data in uBlox binare instead of RTCM.

This is what it look like at rtk2go:
STR;Enebyberg_01;Stockholm;uBlox;uBlox binary msgs;0;;SNIP;SWE;0.00;0.00;1;0;sNTRIP;none;N;N;0;

What am i doing wrong? Is there a config in RTKbase i have missed or is the receiver not configured correct?

**Comment by Stefal** [comment]
Nothing wrong on my side: 
![image](https://user-images.githubusercontent.com/8255984/149668556-b25c1ab0-e1c7-430c-b171-e45285ae855f.png)

**Comment by Stefal** [comment]
I just made a quick test with rtk2go and everything seems ok:

![image](https://user-images.githubusercontent.com/8255984/153496698-cf8f9f8e-6ccd-4d51-9dc1-feb088226686.png)

result on http://monitor.use-snip.com/?hostUrl=rtk2go.com&port=2101:

![image](https://user-images.githubusercontent.com/8255984/153496575-d17448f9-3b93-4916-86fe-c13e776efc5f.png)
