### ISSUE TITLE
Ntrip Caster service did not start

### ISSUE THREAD

**Issue by marcoridder** [Stefal/rtkbase#214]
**Describe the bug**
Ntrip Caster service did not start

**To Reproduce**
1. Update the base from 2.2 -> 2.3.0 -> 2.3.3
2. Setup the Ntrip Caster service options (username, password, mountpoint)
3. Click save
4. Enable the Ntrip Caster service service, button is green. After reload the button is off
5. Diagnostic: str2str_local_ntrip_caster.service: Inactive
6. File service can not be enabled, buttons switch directly to off
7. Rtcm service can not be disabled, i click on 'on' and now it can not switched to off

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.3.3
 - OS: Basegnss from jancelin
 - SBC Raspberry Pi 3B
 - GNSS Device: Ublox F9P
 - Connection type: usb

**Screenshots**
![ec86b93d-c63a-4032-90ec-1250374cfb5e](https://user-images.githubusercontent.com/2344997/160923254-6e8f8c2f-b31f-4951-99be-0a24134b4607.png)
![d9cb7668-5e64-4db8-b2cc-49a28a0520c4](https://user-images.githubusercontent.com/2344997/160923280-a24a84e9-6fa6-42d7-ad68-b5367c858675.png)
![b3bef38f-50bf-48b0-b550-0a37b59a49ce](https://user-images.githubusercontent.com/2344997/160923148-b71a56c4-41c7-489e-943d-7ee733042d01.png)
![6047dbdd-619b-4987-96f1-4a92538e4f30](https://user-images.githubusercontent.com/2344997/160923184-ffdbed46-f463-4d2b-bbe3-36b67f29ba0a.png)
![1cc2679c-92e9-4749-b81a-ff0581f6ae1f](https://user-images.githubusercontent.com/2344997/160923211-86c7ee96-7283-4030-b852-b89898487258.png)

**Comment by Stefal** [comment]
I'll try to repro on my side.

**Comment by Stefal** [comment]
I can't reproduce here.
Did you clear your browser cache? If you don't do it, the javascript code running could be from the old release and could not work with the latest RTKBase release.

**Comment by marcoridder** [comment]
It works thank you. Cache busting could be an idea for future versions?
