### ISSUE TITLE
Wifi power save mode

### ISSUE THREAD

**Issue by GwnDaan** [Stefal/rtkbase#219]
**Describe the bug**
Raspberry Pi goes to wifi power safe mode and then loses connection to the internet for some time. Obviously it will stop providing corrections to the rover when it loses internet connection. Note that this may be system dependant, but as it took me a week or two to figure out the exact problem, I feel like it's worth reporting.

**To Reproduce**
1. Fresh install of RTKBase on Rasberry Pi Zero 2 W
2. Connect to an ntrip service provider using WIFI
3. See error in /var/log/syslog when issue occurs. Can also be seen in the log file below.

**Expected behavior**
Raspberry Pi not going in wifi power save mode when running RTKBase.

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.3.3
 - OS: Raspberry Pi Os
 - SBC: Raspberry Pi Zero 2 W
 - GNSS Device: Ublox F9P
 - Connection type: WIFI 2.4 GHz

**Additional context**
https://www.weigu.lu/sb-computer/raspi_tips_tricks/index.html#link_4 is how I fixed it

The log file is below for when it enters wifi power save mode. This happend approximately 2 times a day until I applied this fix.
[syslog.txt](https://github.com/Stefal/rtkbase/files/8421923/syslog.txt)

**Comment by Stefal** [comment]
Hi!
Thanks for the information.
This problem is outside the RTKBase scope, there is nothing I can do about it, and Wifi is not recommended for a permanent base station.
