### ISSUE TITLE
OpenStreetMap not working on new installation

### ISSUE THREAD

**Issue by MyWebCityDK** [Stefal/rtkbase#223]
I did a new raspberry installation with a new blank SD card, installed RTKbase, updatede all packages etc....
OpenStreetMap is not showing any map when chosing. in website
Ortho HR (fr) is working fine.

**Comment by Stefal** [comment]
Which RTKBase release are you using?
Did you clear the brower cache on the status page?

**Comment by MyWebCityDK** [comment]
We use v2.3.4
After some hours the menu changed and it is now working with "OpenStreetMap (Osm)"
"OpenStreetMap (Hot)" is not working, it is just a blank map.
"Ortho HR (france)" is working fine.

**Comment by Stefal** [comment]
For the HOT layer, it's a knows problem with the tile provider. It's the reason I've added the standard OpenStreetMap layer.
