### ISSUE TITLE
Is there a way to use the non-ublox module?

### ISSUE THREAD

**Issue by jaerabr** [Stefal/rtkbase#226]
Hello guys
I would like to know if there is a way to use rtkbase with a default configuration of the gnss module TAU 1302 in RTCM,
[https://www.allystar.com/en/Uploads/beidou/5e5640db72f6d.pdf](url)
 it is recognized by rtkbase, saves the raw files but without viewing the signal bars.

![parcialtau1302](https://user-images.githubusercontent.com/76694416/173381921-7b442642-8d06-4e4a-b1f3-2299ee088c0f.png)

![rtcmtau1302](https://user-images.githubusercontent.com/76694416/173382012-9169ecbe-5238-435b-8662-47a8cfd54dce.png)

a configuration file
[https://docs.datagnss.com/rtk-board/files/9310_5Hz_good.cmd](url)
[https://docs.datagnss.com/rtk-board/rtk-test/](url)

Thanks for your time and work
google translation

**Comment by jaerabr** [comment]
Yes, I put rtcm

![image](https://user-images.githubusercontent.com/76694416/173882562-21141879-2275-4a0b-b2ec-e4582d9686d4.png)

on windows computer

![image](https://user-images.githubusercontent.com/76694416/173883371-b3a5798b-c172-42a5-8870-8ad621cf60cb.png)

**Comment by GwnDaan** [comment]
Hey,
Are you able to share the information in the `diagnostic` page? It's under the `settings` tab.

Thanks in advance.
![image](https://user-images.githubusercontent.com/29043784/174287378-7ef46b4e-d522-4caf-9562-e667b83d6977.png)

**Comment by jaerabr** [comment]
Hello how are you, diagnostic

[diagnostic TAU1302.txt](https://github.com/Stefal/rtkbase/files/8927056/diagnostic.TAU1302.txt)

**Comment by GwnDaan** [comment]
Hi, sorry for taking so long. It seems to me like the issue is that the settings don't get transfered correctly to rtkrcv.

> [diagnostic TAU1302.txt](https://github.com/Stefal/rtkbase/files/8927056/diagnostic.TAU1302.txt)
```Jun 15 14:45:44 basegnss python3[395]: RTKLIB 9a Attempting to launch rtkrcv...
Jun 15 14:45:44 basegnss python3[395]: rtkrcv already launched
Jun 15 14:45:44 basegnss python3[395]: RTKLIB 9b Attempting to start rtkrcv...
Jun 15 14:45:44 basegnss python3[395]: rtkrcv already started
Jun 15 14:45:44 basegnss python3[395]: Settings sent successfully to rtkrcv
Jun 15 14:45:44 basegnss python3[395]: REFRESH NEEDED !!!!!!!!!!!!!!!!
Jun 15 14:45:44 basegnss python3[395]: RTKLIB 9a Attempting to launch rtkrcv...
Jun 15 14:45:44 basegnss python3[395]: rtkrcv already launched
Jun 15 14:45:44 basegnss python3[395]: RTKLIB 9b Attempting to start rtkrcv...
Jun 15 14:45:44 basegnss python3[395]: rtkrcv already started
```
Here we can see that after the `Settings sent successfully to rtkrcv`. it prompts for `REFRESH NEEDED`. However, when trying to restart rtkrcv it logs `rtkrcv already launched` and `rtkrcv already started`. I therefore think that rtkrcv did **not** restart and the settings are thus never applied.

@Stefal probably know more about this issue (#148).

**Comment by GwnDaan** [comment]
@jaerabr Could you try modifying the file: /home/basegnss/rtkbase/web_app/rtklib_configs/rtkbase_ppp-static_default.conf?

- Step 1: (open file)
`nano /home/basegnss/rtkbase/web_app/rtklib_configs/rtkbase_ppp-static_default.conf`
- Step 2: (edit variable)
  - Find `inpstr1-format`.
  - Try changing it to `rtcm3` **and** `rtcm` (please let me know which one works)
- Step 3: (save file)
Press `crtl+x` then `y` then `enter`
- Step 4: (reboot)
`sudo reboot` or whatever works for you
- Step 5:
Check if the signal bars now work on the site.

Repeat the steps for both rtcm3 and rtcm. Thanks in advance.

**Comment by Stefal** [comment]
Maybe you should just change the receiver format value to `rtcm3` inside the gui.

**Comment by jaerabr** [comment]
Hi, thank you very much, it worked here, making the change in the rtkbase_ppp-static_default.conf file, but it doesn't just need to change the receiver format: rtcm3
when I put it there, only Receiver: rtcm format the script did not restart, sorry my fault now it works perfect
thank you again


![rtkbase](https://user-images.githubusercontent.com/76694416/175541891-19173100-3cec-418a-a6f5-50bfd215a89d.png)
