### ISSUE TITLE
Several diferents users

### ISSUE THREAD

**Issue by messplay** [Stefal/rtkbase#236]
A good feature will be put more users and maybe sourcetable info, some apps do not detect mountpoint i.e NTRIP checker and your app RTCM analyzer neither. By the way, great job people the GUI is amazing Congrats

**Comment by GwnDaan** [comment]
Hi @messplay,

What are the benefits of more users? Sourcetable info is a known issue, see #183. For the apps, what did you input in the fields of the app? For me, NTRIP checker does not work with any caster I know, so that might be an issue with the app itself.
