### ISSUE TITLE
Keep old ntrip configuration in place

### ISSUE THREAD

**Issue by GwnDaan** [Stefal/rtkbase#260]
**Describe the bug**
When upgrading from latest release (v2.3.4) to dev branch, it resets the Ntrip A settings and doesn't keep the old settings in place.

**To Reproduce**
1. Install current release (v2.3.4)
2. Upgrade to dev branch

**Expected behavior**
Keep the configuration for "ntrip a" service the same as the old "ntrip" service. Don't let it reset to default values.

**Comment by Stefal** [comment]
Yes, I know. The migration will be managed during the release to release upgrade process.

**Comment by Stefal** [comment]
(see https://github.com/Stefal/rtkbase/pull/263)
