### ISSUE TITLE
GNSS satellite sky distribution

### ISSUE THREAD

**Issue by exentler** [Stefal/rtkbase#267]
**Describe the solution you'd like**
A want to see a GNSS satellite sky distribution map. 
It can show if satellites are far out and long away from the basestation.

This show the user interface used by Emlid M2:
![bilde](https://user-images.githubusercontent.com/76279565/204603812-6df1909a-c3a1-49f1-aa31-c169a8100c9f.png)

**Comment by Stefal** [comment]
Thanks for the example !

duplicate of #100
