### ISSUE TITLE
GNSS detection from frontend fails

### ISSUE THREAD

**Issue by Stefal** [Stefal/rtkbase#303]
**Describe the bug**
When trying to detect & configure F9P from the frontend, it fails to detect it.

**To Reproduce**
1. Run rtkbase web server with systemd
2. Click on 'Detect & Configure'
3. See "Not detected" 

But, If I start server.py manually, it detects the F9P.

It is linked with the _check_user function in `install.sh` that returns " The logname command return an empty value. Please reboot and retry."

**Comment by hdtopo** [comment]
Amigos estou com um problema quem puder me ajudar fico grato!
Estou usando Orange pi com modulo Ublox M8T e RtkBase, as configurações estão corretas as porta esta tudo ok, consigo criar o arquivo.ubx normalmente, porem estou com problema na pagina STATUS , não consigo receber as coordenadas e nem ver as barras de satélites, meu problema é somente
![arq](https://github.com/Stefal/rtkbase/assets/67793992/5fcdc073-2a54-41ea-9d48-fab0bf348b90)
![config](https://github.com/Stefal/rtkbase/assets/67793992/3fb8a27e-1300-48f9-beb1-267decfc1a26)
![status](https://github.com/Stefal/rtkbase/assets/67793992/08affe86-24e3-472f-9f14-9d4770810ca8)
 na visualização dessa pagina Status o restante esta funcionando normal.
algum puder me ajudar?
