### ISSUE TITLE
Maybe a x86-64 Docker image ?

### ISSUE THREAD

**Issue by myozone** [Stefal/rtkbase#304]
It would good to have a Docker x86-64 image of this in the the future ?

**Comment by Stefal** [comment]
It's not planned, but you can take a look at https://discuss.ardupilot.org/t/rtkbase-with-partner-ardusimple-kit/70567

**Comment by ffries** [comment]
Please reopen this issue as it would be nice to have a Docker solution for Raspberry Pi 2/3/4.
I am interested in moving to a central only using docker-compose to ease installation under Raspberry pi.

Kind regards,
