### ISSUE TITLE
can't connect with browser after update

### ISSUE THREAD

**Issue by Siebenga** [Stefal/rtkbase#305]
After updating to 2.4.1 i can't connect to the rtk base anymore by browser.

With putty it's no problem, but by chrome(or edge) i get the message ERR_CONNECTION_REFUSED.

It feels like a ip bann or something, very strange somebody had the same problem or maybe someone know how to solve?

**Comment by by** [comment]
Did you change the IP address? – Prior to the upgrade, it was hardcoded, now you cant put it into the settings with
	web_port=80
or any port that you prefer…

**Comment by Siebenga** [comment]
and now i can connect but when i click on the settings button i get an internat service error

"the server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application"

**Comment by Stefal** [comment]
I had one case with a security software suite (Sophos) that did strange things. Do you use something like that ? Could you try to connect to the RTKBase web interface from another device ? (smartphone, another computer...)

**Comment by Siebenga** [comment]
already fixet it, did a few things

reflashed the sdd
reinstalled update with putty
did some ip config on the cmd
deleted cookies and stuff

and now it's running like it should. don't make the same mistake again to press the button update lol

**Comment by Stefal** [comment]
You should not have had any problems with the update. 
I'm glad everything is fine now, but we can't know where your problem came from.
