### ISSUE TITLE
 /usr/local/bin/str2str: No such file or directory

### ISSUE THREAD

**Issue by pojolin** [Stefal/rtkbase#306]
**Describe the bug**
I followed the installation instructions and I get a failure to configure GNSS receiver. 

![image](https://user-images.githubusercontent.com/72700571/221947016-b106191a-9a16-4171-a470-be4e93d1af18.png)

I investigated the str2str_tcp.service and I can see that it exits. Running the `run_cast.sh in_serial out_tcp` command, I get the following error : `./run_cast.sh: line 53: /usr/local/bin/str2str: No such file or directory` even though it exists.

**Comment by Stefal** [comment]
What is the output of `file /usr/local/bin/str2str`

And please fill the missing information: 
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Software/Hardware (please complete the following information):**
 - RTKBase release number X.X.X
 - OS: [e.g. Armbian 64bits, Raspberry Pi Os]
 - SBC [e.g. Raspberry Pi 3B+, Orange Pi Zero]
 - GNSS Device: [e.g. Ublox F9P]
 - Connection type: [e.g. usb]

**Comment by pojolin** [comment]
I am sorry for not giving you enough information. This is the current output of `/usr/local/bin/str2str`:

[/usr/local/bin] 
-> % str2str
stream server start
2023/03/01 17:06:30 [CC---]          0 B       0 bps 
^Cstream server stop


**To Reproduce**
To reproduce the behavior, I just run the `run_cast.sh `script with` in_serial ``out_tcp `arguments.

**Expected behavior**
I expect it to function properly as I followed the installation instructions. I am not sure why it can't find the str2str file when it's available in /usr/local/bin/:

ls -lsh
total 8.3M
2.4M -rwxr-xr-x 1 root root 2.4M Feb 27 12:54 convbin
4.0K -rwxr-xr-x 1 root root  212 Feb 27 11:46 distro
4.0K -rwxr-xr-x 1 root root  208 Feb 27 11:46 flask
4.0K -rwxr-xr-x 1 root root  244 Feb 27 11:46 normalizer
4.0K -rwxr-xr-x 1 root root  221 Feb 27 11:44 pip
4.0K -rwxr-xr-x 1 root root  221 Feb 27 11:44 pip3
4.0K -rwxr-xr-x 1 root root  221 Feb 27 11:44 pip3.8
4.0K -rwxr-xr-x 1 root root  220 Feb 27 11:46 pyserial-miniterm
4.0K -rwxr-xr-x 1 root root  222 Feb 27 11:46 pyserial-ports
3.4M -rwxr-xr-x 1 root root 3.4M Feb 27 12:54 rtkrcv
2.6M -rwxr-xr-x 1 root root 2.6M Feb 27 12:54 str2str
4.0K -rwxr-xr-x 1 root root  208 Feb 27 11:44 wheel

**Software/Hardware (please complete the following information):**
    RTKBase release number 2.4.1
    OS: Ubuntu 20.04.5
    SBC: I'm using this x86 computer: Mini PC Windows 10 Pro Intel Celeron N3350
    GNSS Device: Ublox M8P
    Connection type: usb 
    
  I'm also wondering if there is any particular changes I should do the code to make it work with a Piksi GNSS module using an ethernet connection.

Thanks a lot for your help.

**Comment by Stefal** [comment]
RTKBase can't detect and configure a M8P, you should do it manually. In short you should configure it to : 
 - baudrate to 115200 on the output used with the computer
 - enable UBX and disable rtcm/nmea
 - enable RAW and RXM
 - edit settings.conf to set the correct value for com_port= and com_port_settings='115200:8:n:1' and receiver_format='ubx'

Then it should work.

For your Piksi, if it is compatible with RTKLib, yes, it should be possible with some manual modifications.

**Comment by Stefal** [comment]
Yes, you should 
- Stop the web server
- adjust ext_tcp_source='' and ext_tcp_port="" inside settings.conf
- adjust receiver_format='' inside settings.conf
 - edit `/etc/systemd/system/str2str_tcp` and replace `in_serial` with `in_tcp`
 - `sudo systemctl daemon-reload`
 - relaunch services or reboot.

**Comment by pojolin** [comment]
Unfortunately I keep getting this error with str2str_tcp service, no matter with what parameters I launch run_cast.sh with. Have you had issues with this before?

![image](https://user-images.githubusercontent.com/72700571/222492942-e82f0d2f-0b22-4ca3-ade6-a7f4c57a58e7.png)

**Comment by Stefal** [comment]
In `Execstart=/home/nexus/rtkbase/run_cast.sh out_tcp out_tcp`, the first `out_tcp` is wrong, it should be `in_tcp`

**Comment by pojolin** [comment]
You are right. I apologize. I tried some stuff and didn't write correctly in the end. Unfortunately, it doesn't solve the issue I'm having.

![image](https://user-images.githubusercontent.com/72700571/222506625-ff0fdf8e-208e-4e78-af5e-c073ee5d339a.png)

**Comment by Stefal** [comment]
What are the output of:
`which str2str`
and 
`ldd /usr/local/bin/str2str`

**Comment by pojolin** [comment]
Output of `which str2str` : `/usr/local/bin/str2str`

Output of `ldd /usr/local/bin/str2str`:  `not a dynamic executable`

Could this be the issue? I'll investigate but any input would be greatly appreciated!

**Comment by pojolin** [comment]
This is what I get running the `file `command : 

`/usr/local/bin/str2str: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=01f00468da70c88117b94117fe8ce463c73e4df4, with debug_info, not stripped`

**Comment by Stefal** [comment]
Ok, try this:
- in the rtkbase/tools/bin/rtklib_b34g/ folder, delete the x86 folder
- then run `sudo rtkbase/tools/install.sh --rtklib`

It will compile rtklib from the source code.

**Comment by pojolin** [comment]
Thank you! That helped a lot and I don't have the error anymore : 

![image](https://user-images.githubusercontent.com/72700571/223227585-918d7d8f-e1d1-4481-be83-29a245dd8091.png)

Now, when running `run_cast.sh in_tcp out_tcp`, I get `stream server start error`. 

Could this be an issue with the parameters I have put in? (ext_tcp_source, port, receiver_format, etc)

**Comment by Stefal** [comment]
It's strange that you listen and send on the same port (55556). I think you should keep the default 5015 port for tcp_port=
