### ISSUE TITLE
Having issues showing data through the web interface. 

### ISSUE THREAD

**Issue by pojolin** [Stefal/rtkbase#312]
**Describe the bug**
I am trying to make a Ublox M8P GNSS device work with the interface. I'm having issues outputting the data through the web interface.

**To Reproduce**
I run the str2str_tcp service that executes run_cast.sh in_serial out_tcp.

**Expected behavior**
It should be able to connect to the tcp server and send the data to be shown on the web interface. 

**Software/Hardware (please complete the following information):**
- RTKBase release number 2.4.1
- OS: Ubuntu 20.04.5
- SBC: I'm using this x86 computer: Mini PC Windows 10 Pro Intel Celeron N3350
- GNSS Device: Ublox M8P
- Connection type: usb

**Screenshots**
This is what I get in the str2str_tcp status screen:
![image](https://user-images.githubusercontent.com/72700571/225700347-a74fbbbd-c80b-48d2-bb0a-60344d4ab0a2.png)

These are my settings on the web interface:
![image](https://user-images.githubusercontent.com/72700571/225672185-19a87fd6-4472-4fa5-8a83-a7ea7459234a.png)

Thank you

**Comment by Stefal** [comment]
Is your M8P configured to output RAWX and SFRBX ?
