### ISSUE TITLE
IGN PPP compute failure

### ISSUE THREAD

**Issue by Stefal** [Stefal/rtkbase#314]
**Describe the bug**
A rinex file sent to the IGN PPP online service fails because there is more than 24H observables.
A workaround is to delete 2 or 3 of the last observables to stay below 24H duration.

**Comment by Stefal** [comment]
To use `-te` parameter with convbin, full date is needed : `-te 2023/04/10 07:00:00`
I tried `-span 1` to limit time span but it doesn't work.

**Comment by nubotix** [comment]
I forgot to mention I'm using RTKBase v2.4.1

 CSRS-PPP SPARK  was just succesfully processed the truncated file. (It rejected my previous untruncated attempts)

Thanks for your really useful software!

Dafydd

**Comment by Stefal** [comment]
I just wanted to warn you that a lot of PPP tool works only with L1+L2 data. The M8T is L1 only.

**Comment by Stefal** [comment]
One way to check if the rinex timespan is too long is to check these two lines : 
TIME OF FIRST OBS
and
TIME OF LAST OBS

then use a bash command like cut/awk/split/csplit

**Comment by Stefal** [comment]
I've set file overlap default value to 0s
