### ISSUE TITLE
Allow 1007 message

### ISSUE THREAD

**Issue by 82Jussi** [Stefal/rtkbase#322]
At least Topcon AGI-4 needed the 1007 alongside 1008, to be able to get the stable RTK fix.

I would like to be able to write to rtcm messages 1007 like other messages and get that message sent by that.

![image](https://github.com/Stefal/rtkbase/assets/136469908/ebd38265-21c3-4f2a-afec-dfb6b0ed636d)

**Comment by Stefal** [comment]
> I would like to add 1007 message to rtcm message list and it would be sent with correction data. Am I wrong that it is not sent today?

It is sent if you add it to the message list, like you did on your first screenshot.

**Comment by 82Jussi** [comment]
Then this request is not needed. Thank you. Sorry for confusion.
