### ISSUE TITLE
Space in 'receiver' variable not escaped correctly

### ISSUE THREAD

**Issue by Aikhjarto** [Stefal/rtkbase#323]
**Describe the bug**
However, spaces in the corresponding variable `receiver` in `settings.conf`, e.g. `receiver='u-blox 8'` are not escaped.
The non-escaped space does not cause str2str to fail, but it prematurely ends the source-table entries argument, stripping important flags like the authentication flag.

**To Reproduce**
1. Have a space in the variable `receiver` in `settings.conf`, e.g. `receiver='u-blox 8'` and set `local_ntripc_user` and `local_ntripc_pwd` to something non-empty. 
2. Start `str2str_local_ntrip_caster.service`
3. Have any tool, e.g. `gpsd`, connect to the local ntrip caster while watching the outcome of `tcpdump -A -vvvv tcp port 2101`
4. If the tool used for trying to connect adheres to the ntrip standard, you will get a connection error. E.g., GPSd will fail with `gpsd:ERROR: not authorized for Ntrip stream ("Authorization: Basic" is not transfered)` since, as visible with tcpdump, the source-table is cropped. Note: u-center does not adhere to the ntrip standard when it comes to the authentication flag and does not produce an error.

Corresponding bugreport at GPSd: https://gitlab.com/gpsd/gpsd/-/issues/248

For debugging, the arguments for str2str can be shown using `cat /proc/xxxxx/cmdline | tr '\000' '\n'`, where xxxxx is the the PID of str2str.
This also shows that the space in the variable `receiver` are not escaped correctly.

**Expected behavior**
A combination of username and password and spaces in the receiver string should work, as spaces in the generator string in the ntrip source-table are explicitly allowed, see https://igs.bkg.bund.de/root_ftp/NTRIP/documentation/NtripDocumentation.pdf .

**Software/Hardware**
 - RTKBase release number 2.4.1
 - OS: Raspberry Pi Os (Debian 11)
 - SBC Raspberry Pi Zero
 - GNSS Device:  Ublox 8 and Ublox 9
 - Connection type: USB

**Comment by Stefal** [comment]
In the meantime I could prohibit space in the receiver form entry.
