### ISSUE TITLE
Caster support

### ISSUE THREAD

**Issue by GOOD-Stuff** [Stefal/rtkbase#325]
This project looks really cool and useful!
Do I understand correctly that with _str2str_local_ntrip_caster.service_ my base can act as a NTRIP Caster?

**Comment by Stefal** [comment]
You're right, but you will have to set your router correctly to accept an incoming connection from the internet.

**Comment by GOOD-Stuff** [comment]
Thanks for the quick answer!
Do I need to change anything in _str2str_local_ntrip_caster.service_ for this case?

**Comment by Stefal** [comment]
> Thanks for the quick answer! Do I need to change anything in _str2str_local_ntrip_caster.service_ for this case?

No, the parameters are available on the web interface.
