### ISSUE TITLE
Ublox M8t Orange pi (Status problems)

### ISSUE THREAD

**Issue by hdtopo** [Stefal/rtkbase#326]
Amigos estou com um problema quem pode me ajudar fico grato!
Estou usando Orange pi com módulo Ublox M8T e RtkBase, as configurações estão corretas como porta esta tudo ok, consigo criar o arquivo.ubx normalmente, porem estou com problema na pagina STATUS , não consigo receber as coordenadas e nem ver as barras de satélites, meu problema é somente na visualização dessa página Status o restante esta funcionando normalmente. algum pode me ajudar?
![arq](https://github.com/Stefal/rtkbase/assets/67793992/d4bc4783-6467-41be-8f9d-e9e9d4867c03)
![config](https://github.com/Stefal/rtkbase/assets/67793992/53b11c4e-94a2-4815-a652-6c0c40b9a2a9)
![status](https://github.com/Stefal/rtkbase/assets/67793992/09018d96-56c5-4a4c-9736-bbec7d275a3a)

**Comment by jaerabr** [comment]
Imagino que não tenha mas suporte nativo para o m8t nas versoes mais novas do RtkBase use uma versão mais antiga tipo a Rtkbase 2.2.0 
![image](https://github.com/Stefal/rtkbase/assets/76694416/761e23d6-9625-4a3c-9bb7-2ba373930c25)
![image](https://github.com/Stefal/rtkbase/assets/76694416/3fb959d2-c40c-4d8e-9aef-1ff4067146b7)

**Comment by jaerabr** [comment]
Na rpi zero funciona na 2.4.1

![image](https://github.com/Stefal/rtkbase/assets/76694416/8850fce2-b5af-4b42-8e88-bd62327fb947)
