### ISSUE TITLE
Confusion between SVIN and HPPOSLLH coordinates

### ISSUE THREAD

**Issue by smirkingman** [Stefal/rtkbase#327]
I have a base station Ublox_ZED-F9P, [here](http://rtk2go.com:2101/SNIP::MOUNTPT?baseName=chgevymg8a) running perfectly for years, this is a remarkably professional piece of software.

Question: 
I wanted to re-check the base position by re-running a 24-hour averaging; tectonic plate movement? >;-)

My SVIN coordinates are 46.17067488, 6.1615077095.

I ran file logging for 24 hours and downloaded the UBX files.
When I dump them the HPPOSLLH lat/lon is always the same, fixed value: 46.17067488**2**, 6.1615077**16**.
I presume this is the value sent to RTK2GO, which makes sense.
OK, it's only half a millimetre away but it's not **exactly** the same, no big deal though.

However, I would have expected the lat/lon to wander a little, as it does on the status page, for example 46.170674882, 6.161507716 (about 50cm away) and that those values would be output in the HPPOSLLH messages.

Have I mis-understood something here?

Merci et bravo pour ce beau boulot.

**Comment by Stefal** [comment]
Hi !
The coordinates sent to RTK2GO are the one you have entered in the main service. HPPOSLLH or any other ubx message are not sent outside of RTKBase.

I you want to check your "actual" position, you should reprocess the ubx or rinex file with a post process ppp or rtk tool. (nrcan, ign ppp, opus, ....)
