### ISSUE TITLE
Confusion between basegnss and ucenter

### ISSUE THREAD

**Issue by famfam2812** [Stefal/rtkbase#328]
Hey.

When i connect to my f9p over the internet in ucenter, i says its in "TIME" and the location stays the same. But when i check the status page in basegnss, it keeps moving. What am i suppossed to believe, or am i doing something wrong?

**Comment by Stefal** [comment]
hi !
It's strange that your F9P is in time mode, as it's not a parameter set by RTKBase.

RTKBase use only the Raw data from the F9P, all other ubx message are not used, and the internal engine that compute a position is not used at all.

What you see on the status page is only a realtime position process with RTKLib, and is displayed here just for information and to check that the transmitted coordinates (entered in the main service on the settings page) and the realtime position are almost identical.
