### ISSUE TITLE
Ntrip A Service will not stay on.

### ISSUE THREAD

**Issue by carkah** [Stefal/rtkbase#339]
**Describe the bug**
I have Main Service and Ntrip A Service configured correctly on toggled on.  I go to the status page and when I go back to settings Ntrip A service is toggled off but Main service is still on.  It actually does it for any of the toggles now that I have tried some more

**To Reproduce**
1. Go to settings
2. Click on to toggle for Ntrip service A
3.  Click on status
4. click on settings
5. See error

**Expected behavior**

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.2.2
 - OS: Debian 11 (Bullseye)
 - SBC Xunlong Orange Pi Zero
 - GNSS Device: U-blox_ZED-F9P - 1.11
 - Connection type: usb

**Comment by Stefal** [comment]
Hi!
Please copy paste here what you see in the diagnostic page about str2str_tcp and str2str_ntrip_A

**Comment by carkah** [comment]
I think this is what you are looking for.  let me know if you need something else

str2str_tcp.service : Active
● str2str_tcp.service - RTKBase Tcp
Loaded: loaded (/etc/systemd/system/str2str_tcp.service; enabled; vendor preset: enabled)
Active: active (running) since Sat 2023-11-04 04:11:50 UTC; 9h ago
Process: 1143 ExecStart=/home/basegnss/rtkbase/run_cast.sh in_serial out_tcp (code=exited, status=0/SUCCESS)
Main PID: 1150 (str2str)
Tasks: 2 (limit: 906)
Memory: 352.0K
CPU: 5min 24.234s
CGroup: /system.slice/str2str_tcp.service
└─1150 /usr/local/bin/str2str -in serial://ttyACM0:115200:8:n:1#ubx -out tcpsvr://:5015 -b 1 -t 0 -fl /home/basegnss/rtkbase/logs/str2str_tcp.log

Nov 04 14:04:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:04:08 basegnss run_cast.sh[1150]: 2023/11/04 14:04:27 [CC---] 160344392 B 32908 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:05:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:05:08 basegnss run_cast.sh[1150]: 2023/11/04 14:05:27 [CC---] 160579992 B 32892 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:06:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:06:08 basegnss run_cast.sh[1150]: 2023/11/04 14:06:27 [CC---] 160815592 B 31936 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:07:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:07:08 basegnss run_cast.sh[1150]: 2023/11/04 14:07:27 [CC---] 161051192 B 31904 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:08:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:08:08 basegnss run_cast.sh[1150]: 2023/11/04 14:08:27 [CC---] 161288248 B 32159 bps (0) /dev/ttyACM0 (1) 2 clients

-- Journal begins at Sat 2023-11-04 04:11:30 UTC, ends at Sat 2023-11-04 14:08:36 UTC. --
Nov 04 04:11:30 basegnss run_cast.sh[570]: stream server start
Nov 04 13:05:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:05:08 basegnss run_cast.sh[1150]: 2023/11/04 13:05:26 [CC---] 146132236 B 36973 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:06:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:06:08 basegnss run_cast.sh[1150]: 2023/11/04 13:06:26 [CC---] 146402400 B 37288 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:07:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:07:08 basegnss run_cast.sh[1150]: 2023/11/04 13:07:26 [CC---] 146674296 B 36792 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:08:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:08:08 basegnss run_cast.sh[1150]: 2023/11/04 13:08:26 [CC---] 146943768 B 36699 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:09:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:09:08 basegnss run_cast.sh[1150]: 2023/11/04 13:09:26 [CC---] 147212052 B 36619 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:10:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:10:08 basegnss run_cast.sh[1150]: 2023/11/04 13:10:26 [CC---] 147480268 B 36808 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:11:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:11:08 basegnss run_cast.sh[1150]: 2023/11/04 13:11:27 [CC---] 147747140 B 35802 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:12:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:12:08 basegnss run_cast.sh[1150]: 2023/11/04 13:12:27 [CC---] 148014548 B 35952 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:13:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:13:08 basegnss run_cast.sh[1150]: 2023/11/04 13:13:27 [CC---] 148279844 B 37016 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:14:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:14:08 basegnss run_cast.sh[1150]: 2023/11/04 13:14:27 [CC---] 148544444 B 36416 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:15:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:15:08 basegnss run_cast.sh[1150]: 2023/11/04 13:15:27 [CC---] 148805900 B 35244 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:53:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:53:08 basegnss run_cast.sh[1150]: 2023/11/04 13:53:27 [CC---] 157856704 B 30309 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:54:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:54:08 basegnss run_cast.sh[1150]: 2023/11/04 13:54:27 [CC---] 158078428 B 30096 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:55:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:55:08 basegnss run_cast.sh[1150]: 2023/11/04 13:55:27 [CC---] 158301164 B 30561 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:56:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:56:08 basegnss run_cast.sh[1150]: 2023/11/04 13:56:27 [CC---] 158526064 B 30594 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:57:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:57:08 basegnss run_cast.sh[1150]: 2023/11/04 13:57:27 [CC---] 158751072 B 30640 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:58:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:58:08 basegnss run_cast.sh[1150]: 2023/11/04 13:58:27 [CC---] 158976144 B 30582 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 13:59:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 13:59:08 basegnss run_cast.sh[1150]: 2023/11/04 13:59:27 [CC---] 159200736 B 30515 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:00:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:00:08 basegnss run_cast.sh[1150]: 2023/11/04 14:00:27 [CC---] 159425296 B 28597 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:01:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:01:08 basegnss run_cast.sh[1150]: 2023/11/04 14:01:27 [CC---] 159649856 B 30356 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:02:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:02:08 basegnss run_cast.sh[1150]: 2023/11/04 14:02:27 [CC---] 159874872 B 32159 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:03:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:03:08 basegnss run_cast.sh[1150]: 2023/11/04 14:03:27 [CC---] 160108792 B 32958 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:04:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:04:08 basegnss run_cast.sh[1150]: 2023/11/04 14:04:27 [CC---] 160344392 B 32908 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:05:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:05:08 basegnss run_cast.sh[1150]: 2023/11/04 14:05:27 [CC---] 160579992 B 32892 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:06:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:06:08 basegnss run_cast.sh[1150]: 2023/11/04 14:06:27 [CC---] 160815592 B 31936 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:07:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:07:08 basegnss run_cast.sh[1150]: 2023/11/04 14:07:27 [CC---] 161051192 B 31904 bps (0) /dev/ttyACM0 (1) 127.0.0.1
Nov 04 14:08:08 basegnss systemd-journald[467]: Suppressed 11 messages from str2str_tcp.service
Nov 04 14:08:08 basegnss run_cast.sh[1150]: 2023/11/04 14:08:27 [CC---] 161288248 B 32159 bps (0) /dev/ttyACM0 (1) 2 clients

str2str_ntrip_A.service : Inactive
● str2str_ntrip_A.service - RTKBase Ntrip A
Loaded: loaded (/etc/systemd/system/str2str_ntrip_A.service; enabled; vendor preset: enabled)
Active: inactive (dead) since Sat 2023-11-04 04:46:19 UTC; 9h ago
Process: 2595 ExecStart=/home/basegnss/rtkbase/run_cast.sh in_tcp out_caster_A (code=exited, status=0/SUCCESS)
Main PID: 2602 (code=exited, status=0/SUCCESS)
CPU: 86ms

-- Journal begins at Sat 2023-11-04 04:11:30 UTC, ends at Sat 2023-11-04 14:08:36 UTC. --
Nov 04 04:11:30 basegnss run_cast.sh[575]: usage: str2str [-in stream] [-out stream [-out stream...]] [options]
Nov 04 04:11:30 basegnss run_cast.sh[575]: Input data from a stream and divide and output them to multiple streams
Nov 04 04:11:30 basegnss run_cast.sh[575]: The input stream can be serial, tcp client, tcp server, ntrip client, or
Nov 04 04:11:30 basegnss run_cast.sh[575]: file. The output stream can be serial, tcp client, tcp server, ntrip server,
Nov 04 04:11:30 basegnss run_cast.sh[575]: or file. str2str is a resident type application. To stop it, type ctr-c in
Nov 04 04:11:30 basegnss run_cast.sh[575]: console if run foreground or send signal SIGINT for background process.
Nov 04 04:11:30 basegnss run_cast.sh[575]: if run foreground or send signal SIGINT for background process.
Nov 04 04:11:30 basegnss run_cast.sh[575]: if both of the input stream and the output stream follow #format, the
Nov 04 04:11:30 basegnss run_cast.sh[575]: format of input messages are converted to output. To specify the output
Nov 04 04:11:30 basegnss run_cast.sh[575]: messages, use -msg option. If the option -in or -out omitted, stdin for
Nov 04 04:11:30 basegnss run_cast.sh[575]: input or stdout for output is used. If the stream in the option -in or -out
Nov 04 04:11:30 basegnss run_cast.sh[575]: is null, stdin or stdout is used as well.
Nov 04 04:11:30 basegnss run_cast.sh[575]: Command options are as follows.
Nov 04 04:11:30 basegnss run_cast.sh[575]: -in stream[#format] input stream path and format
Nov 04 04:11:30 basegnss run_cast.sh[575]: -out stream[#format] output stream path and format
Nov 04 04:11:30 basegnss run_cast.sh[575]: stream path
Nov 04 04:11:30 basegnss run_cast.sh[575]: serial : serial://port[:brate[:bsize[:parity[:stopb[:fctr]]]]][#tcp_port]
Nov 04 04:11:30 basegnss run_cast.sh[575]: tcp server : tcpsvr://:port
Nov 04 04:11:30 basegnss run_cast.sh[575]: tcp client : tcpcli://addr[:port]
Nov 04 04:11:30 basegnss run_cast.sh[575]: ntrip client : ntrip://[user[:passwd]@]addr[:port][/mntpnt]
Nov 04 04:11:30 basegnss run_cast.sh[575]: ntrip server : ntrips://[:passwd@]addr[:port]/mntpnt[:str] (only out)
Nov 04 04:11:30 basegnss run_cast.sh[575]: ntrip caster : ntripc://[user:passwd@][:port]/mntpnt[:srctbl] (only out)
Nov 04 04:11:30 basegnss run_cast.sh[575]: file : [file://]path[::T][::+start][::xseppd][::S=swap]
Nov 04 04:11:30 basegnss run_cast.sh[575]: format
Nov 04 04:11:30 basegnss run_cast.sh[575]: rtcm2 : RTCM 2 (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: rtcm3 : RTCM 3
Nov 04 04:11:30 basegnss run_cast.sh[575]: nov : NovAtel OEMV/4/6,OEMStar (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: cnav : ComNav (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: ubx : ublox LEA-4T/5T/6T/8/9 (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: swiftnav : SwiftNav Piksi Multi
Nov 04 04:11:30 basegnss run_cast.sh[575]: hemis : Hemisphere Eclipse/Crescent (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: stq : SkyTraq S1315F (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: javad : Javad (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: nvs : NVS BINR (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: binex : BINEX (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: rt17 : Trimble RT17 (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: sbf : Septentrio SBF (only in)
Nov 04 04:11:30 basegnss run_cast.sh[575]: -msg "type[(tint)][,type[(tint)]...]"
Nov 04 04:11:31 basegnss run_cast.sh[575]: rtcm message types and output intervals (s)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -sta sta station id
Nov 04 04:11:31 basegnss run_cast.sh[575]: -opt opt receiver dependent options
Nov 04 04:11:31 basegnss run_cast.sh[575]: -s msec timeout time (ms) [10000]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -r msec reconnect interval (ms) [10000]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -n msec nmea request cycle (m) [0]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -f sec file swap margin (s) [30]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -c file input commands file [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -c1 file output 1 commands file [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -c2 file output 2 commands file [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -c3 file output 3 commands file [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -c4 file output 4 commands file [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -p lat lon hgt station position (latitude/longitude/height) (deg,m)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -px x y z station position (x/y/z-ecef) (m)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -a antinfo antenna info (separated by ,)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -i rcvinfo receiver info (separated by ,)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -o e n u antenna offset (e,n,u) (m)
Nov 04 04:11:31 basegnss run_cast.sh[575]: -l local_dir ftp/http local directory []
Nov 04 04:11:31 basegnss run_cast.sh[575]: -x proxy_addr http/ntrip proxy address [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -b str_no relay back messages from output str to input str [no]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -t level trace level [0]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -fl file log file [str2str.trace]
Nov 04 04:11:31 basegnss run_cast.sh[575]: -h print help

**Comment by carkah** [comment]
![Screenshot_20230211_081853](https://github.com/Stefal/rtkbase/assets/62409763/f8e60c80-0f76-42d4-99a7-db0874b93298)
![Screenshot 2023-11-04 091239](https://github.com/Stefal/rtkbase/assets/62409763/e1f3a727-ad0a-4d5e-8d90-b7efe30b92b6)

**Comment by Stefal** [comment]
The Ntrip service refuse your parameters but I don't know why. 
 - Do you use only ASCII char for your mount name (without space or special char)?
 - Are the coordinates 'lat long ele' with only digits, dot, and '-' if needed ?

**Comment by carkah** [comment]
ahhh I did not have an elevation entered in!  Thank You.  I will for sure sponsor you for the help.  Is elevation in feet, meters, or other?

**Comment by Stefal** [comment]
> ahhh I did not have an elevation entered in! Thank You. I will for sure sponsor you for the help. Is elevation in feet, meters, or other?

in meters (SI) please.
