### ISSUE TITLE
Right RAW messages types for RTKbase

### ISSUE THREAD

**Issue by Jaxz13** [Stefal/rtkbase#343]
I try to make base station based on RTK3B [https://www.ardusimple.com/product/simplertk3b-x5/](url) and RTKbase.

I get messages from RTK3B to raspberry uart1, /dev/ttyS0. Main sevice stays green in RTKbase, but nothing happens in status page - no satellite bars or location information at all.

What are right messages types for RTKbase?
![rtcm](https://github.com/Stefal/rtkbase/assets/151033616/797fd342-069b-4c31-9bc9-07921df22260)

What is right receiver format in main settings?
![receiver](https://github.com/Stefal/rtkbase/assets/151033616/8d5b9ca9-e878-41bb-9752-3f114de5e422)

**Comment by jaerabr** [comment]
Hello, your gnss module is sending rtcm3 to rtkase, so change ubx to rtcm3 in main service

![image](https://github.com/Stefal/rtkbase/assets/76694416/b3e80cf6-fdbc-4069-8788-54a784324d8b)

**Comment by Stefal** [comment]
@jaerabr is right

I'm working on a new RTKBase release which should be able to use the Mosaic X5 with raw messages. It will be available next year.

**Comment by Jaxz13** [comment]
> @jaerabr is right
> 
> I'm working on a new RTKBase release which should be able to use the Mosaic X5 with raw messages. It will be available next year.

Sounds good that Mosaic integration.. 

Actually I need (or my customer needs) base station with two differrent base coordinates height setting -> and two different NTRIP services (same Lat and Lon coordinates, different height). My thinking is to do one NTRIP service in mosaic X5 and other in RTKbase.

If that setting, as described above is possible to implement in RTKbase, I will be happy.

**Comment by Stefal** [comment]
> Actually I need (or my customer needs) base station with two differrent base coordinates height setting -> and two different NTRIP services (same Lat and Lon coordinates, different height). 
> If that setting, as described above is possible to implement in RTKbase, I will be happy.

Different height for the 2 ntrip services inside RTKBase is not possible. 

But you can hack RTKBase :
 - add a new "position" value in settings.conf, ie "position_B"
 - edit `out_caster_B="ntrips://:${svr_pwd_b}@${svr_addr_b}:${svr_port_b}/${mnt_name_b}#rtcm3 -msg ${rtcm_msg_b} -p ${position}"` to use this new variable :  `out_caster_B="ntrips://:${svr_pwd_b}@${svr_addr_b}:${svr_port_b}/${mnt_name_b}#rtcm3 -msg ${rtcm_msg_b} -p ${position_B}"`

And it should work 😄

**Comment by Jaxz13** [comment]
Now there is beams.. but still no position. Waiting more than 10 minutes that position after startup. Position seen right in Mosaic setting page.

<img width="584" alt="palkit" src="https://github.com/Stefal/rtkbase/assets/151033616/2abcab07-fd4e-4fb0-968f-6bda04c3be71">

**Comment by Jaxz13** [comment]
> > Actually I need (or my customer needs) base station with two differrent base coordinates height setting -> and two different NTRIP services (same Lat and Lon coordinates, different height).
> > If that setting, as described above is possible to implement in RTKbase, I will be happy.
> 
> Different height for the 2 ntrip services inside RTKBase is not possible.
> 
> But you can hack RTKBase :
> 
>     * add a new "position" value in settings.conf, ie "position_B"
> 
>     * inside run_cast_.sh edit `out_caster_B="ntrips://:${svr_pwd_b}@${svr_addr_b}:${svr_port_b}/${mnt_name_b}#rtcm3 -msg ${rtcm_msg_b} -p ${position}"` to use this new variable :  `out_caster_B="ntrips://:${svr_pwd_b}@${svr_addr_b}:${svr_port_b}/${mnt_name_b}#rtcm3 -msg ${rtcm_msg_b} -p ${position_B}"`
> 
> 
> And it should work 😄

Thanks for the info! I will try that.

**Comment by Jaxz13** [comment]
> Now there is beams.. but still no position. Waiting more than 10 minutes that position after startup. Position seen right in Mosaic setting page.
> <img alt="palkit" width="584" src="https://user-images.githubusercontent.com/151033616/283506453-2abcab07-fd4e-4fb0-968f-6bda04c3be71.png">

Still no position in status page.. What are the right settings in Mosaic-x5?
<img width="861" alt="mosaic" src="https://github.com/Stefal/rtkbase/assets/151033616/001bc9c0-f9ab-4d6e-b5f8-9359f72084fc">

RTKBase gets position from mosaic but setting in RTKbase - Main service - base coordinates, does not effect anything in NTRIP services. Ntrip service works but Base station position is same what position is seen in mosaic-X5.

**Comment by jaerabr** [comment]
Good morning, do a test, disable the rtcm messages that are sent to the ECEF location in mosaic-X5, example: 1005, 1006 and 1032, I do this with the unicore um980 module and it works

**Comment by Jaxz13** [comment]
> Good morning, do a test, disable the rtcm messages that are sent to the ECEF location in mosaic-X5, example: 1005, 1006 and 1032, I do this with the unicore um980 module and it works

Thanks for the reply... Tried to disable those mentioned messages. Still not working.

What RTCM3 messages sends your unicore um980 to rtkbase?

**Comment by jaerabr** [comment]
> > Bom dia, faça um teste, desative as mensagens rtcm que são enviadas para o local ECEF no mosaico-X5, exemplo: 1005, 1006 e 1032, faço isso com o módulo unicore um980 e funciona
> 
> Obrigado pela resposta... Tentei desativar as mensagens mencionadas. Ainda não funciona.
> 
> Quais mensagens RTCM3 enviam seu unicore um980 para rtkbase?

I leave the 1019, 1020, 1042, 1046, 1077, 1087, 1097 and 1124 active, all at 1hz

**Comment by Jaxz13** [comment]
> > > Bom dia, faça um teste, desative as mensagens rtcm que são enviadas para o local ECEF no mosaico-X5, exemplo: 1005, 1006 e 1032, faço isso com o módulo unicore um980 e funciona
> > 
> > 
> > Obrigado pela resposta... Tentei desativar as mensagens mencionadas. Ainda não funciona.
> > Quais mensagens RTCM3 enviam seu unicore um980 para rtkbase?
> 
> I leave the 1019, 1020, 1042, 1046, 1077, 1087, 1097 and 1124 active, all at 1hz

It needed those  1019, 1020, 1042, 1046.

**Comment by Stefal** [comment]
Could we close this issue?
