### ISSUE TITLE
RTCM Message 1045 not working

### ISSUE THREAD

**Issue by carkah** [Stefal/rtkbase#362]
**Describe the bug**
I have these messages typed into my Ntrip A service:
1004,1005(10),1006,1008(10),1012,1019,1020,1033(10),1042,1045,1046,1074,1084,1094,1230
, and when I run a test off my base station I receive messages: 1004,1005,1006,1008,1012,1019,1020,1033,1042,1046, 1074,1084,1094,1230 but no 1045.  I have my receiver options set to -TADJ=1

**To Reproduce**
1. Enter 1004,1005(10),1006,1008(10),1012,1019,1020,1033(10),1042,1045,1046,1074,1084,1094,1230 in rtcm messages
2. Run the base
3. use a rtcm tester software to watch incoming messages

**Expected behavior**
No 1045 messages are sent

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.5.0
 - OS: Debian 11 (Bullseye)
 - SBC: Xunlong Orange Pi Zero
 - GNSS Device: U-blox_ZED-F9P - 1.11
 - Connection type: usb

**Screenshots**
![Screenshot 2024-02-02 005900](https://github.com/Stefal/rtkbase/assets/62409763/64cd5031-c89d-4176-83f7-f99a7d3ca800)
![message count](https://github.com/Stefal/rtkbase/assets/62409763/a27f4d75-6d46-4db1-accb-5581be9b939c)

**Additional context**

**Comment by Stefal** [comment]
RTKBase 2.5.0 with a Septentrio Mosaic X5
![image](https://github.com/Stefal/rtkbase/assets/8255984/01ad47c2-e7e6-436b-bb15-cbe55a403b2d)

We can close this issue
