### ISSUE TITLE
Base Coordinates showing invalid after 2.5.0 update

### ISSUE THREAD

**Issue by carkah** [Stefal/rtkbase#363]
**Describe the bug**
After I updated to 2.5.0 my base coordinates show invalid and wont let me save any changes made to any of the other categories, however, base is still showing up correctly on rtk2go and on the status page.  I have 1 space in between lat and long and long and elevation

**To Reproduce**
1. update to 2.5.0 and error appeared.

**Software/Hardware (please complete the following information):**
 - RTKBase release number X.X.X
 - OS: Debian 11 (Bullseye)
 - SBC Xunlong Orange Pi Zero
 - GNSS Device: U-blox_ZED-F9P - 1.11
 - Connection type: usb

**Screenshots**
![Screenshot 2024-02-02 013312](https://github.com/Stefal/rtkbase/assets/62409763/878a8045-ccd8-469b-beb9-279008cd9559)
![Screenshot 2024-02-02 013632](https://github.com/Stefal/rtkbase/assets/62409763/eff358bd-84c0-47b3-a86b-e4dad52052ae)

**Additional context**

**Comment by Stefal** [comment]
Do you have at least two digits for your elevation value ?

**Comment by carkah** [comment]
I did not, however, I tried 7.0 and 11 and neither were accepted

**Comment by Stefal** [comment]
> I did not, however, I tried 7.0 and 11 and neither were accepted

did you try `7.00` ? (it's two digits after the comma)

**Comment by carkah** [comment]
Ah yes that is it.  Thank you
