### ISSUE TITLE
 If mount and password are both TCP use TCP-client instead of NTRIP-server

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#373]
To use [rtkdirect](https://rtkdirect.com/), RtkBase must be connected as a TCP client, and not as an NTRIP server.

So I modified run_cast.sh so that when mountpoint and password are both equal to TCP, the connection goes as tcpcli:// and not as ntrips://

[commit-TCP_CLIENT.txt](https://github.com/Stefal/rtkbase/files/14601384/commit-TCP_CLIENT.txt)

**Comment by Stefal** [comment]
closed because rtkdirect switched to ntrip
