### ISSUE TITLE
/sys/firmware/devicetree/base/model: No such file or directory

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#374]
When installing on an X86 on an RPI file system image, we receive the message "/usr/local/rtkbase/rtkbase_install.sh: line 178: /sys/firmware/devicetree/base/model: No such file or directory"

Please check, is this file exists before read.

RTKBase 2.5.0

**Comment by Jef239** [comment]
Also /usr/local/rtkbase/rtkbase/tools/opizero_temp_offset.sh: line 5: /sys/firmware/devicetree/base/model: No such file or directory

**Comment by Stefal** [comment]
Thanks for the issue.
