### ISSUE TITLE
Add U Center Support to Pi image

### ISSUE THREAD

**Issue by craisbeck** [Stefal/rtkbase#385]
Is there any way that the Pi image can be set up to forward the USB port info onto the TCP port so a person could use the network function of UCenter to monitor that the station is working correctly?

**Comment by Stefal** [comment]
It's already available. Connect U-Center to the base station ip address, on port 5015.

It may change in the future.

**Comment by craisbeck** [comment]
Is that documented somewhere because we never seen it in any readme

**Comment by Stefal** [comment]
You can read this issue too : https://github.com/Stefal/rtkbase/issues/188

**Comment by craisbeck** [comment]
We wrote our own node and socat interface quick.   Thats where the comment came from.  But now we will use your build it one.    I have a discourse going because while using your base I am unable to ever get a rtk lock.   I am able to get a rtk lock when using a caster.

I was hoping to be able to use your tcp branch to get local corrections and caster corrections.   I read somewhere that they can alternate back and forth.

The later has nothing to do with not getting a rtk lock.   I’m not sure how to fix that.

Best Regards from my tiny keyboard,
Cory Raisbeck
Boxlogix Automation, Owner
________________________________
