### ISSUE TITLE
How do I configure TMODE3/ECEF?

### ISSUE THREAD

**Issue by mvrius** [Stefal/rtkbase#388]
If using the base station as a correction data RTCM streamer, if I'm understanding the workflow right, I have to configure F9P in TMODE3 and provide the precise coordinates from CSRS-PPP service.

Do I do that using the base coordinates field? Or do I have to configure UBX separately via U-Center?

Thanks!

**Comment by Stefal** [comment]
No, you don't have to set a single thing in the F9P if it was autoconfigured by RTKBase.
