### ISSUE TITLE
ntrip v2

### ISSUE THREAD

**Issue by vk3vs** [Stefal/rtkbase#406]
Gday,

Great software

How hard would it be to add ntrip v2 compatibility for pusing to a caster

Ta

Matt

**Comment by Jef239** [comment]
May be use https://github.com/nunojpg/ntripserver instead of str2str?

**Comment by vk3vs** [comment]
I was hoping to use the nice guiSent from my Galaxy
-------- Original message --------From: Jef239 ***@***.***> Date: 7/7/24  05:02  (GMT+10:00) To: Stefal/rtkbase ***@***.***> Cc: vk3vs ***@***.***>, Author ***@***.***> Subject: Re: [Stefal/rtkbase] ntrip v2 (Issue #406) 
May be use https://github.com/nunojpg/ntripserver instead of str2str?

**Comment by Stefal** [comment]
I'm waiting for RTKLib Ntrip 2 support.

**Comment by Jef239** [comment]
> I'm waiting for RTKLib Ntrip 2 support.

I think that in about two weeks I will make it in [UM980_RPI_Hat_RtkBase](https://github.com/GNSSOEM/UM980_RPI_Hat_RtkBase)
