### ISSUE TITLE
Configure for Mosaic X5 not work at all

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#412]
Configure for Mosaic X5 not work at all

![image](https://github.com/Stefal/rtkbase/assets/154726922/f2d11f18-15dc-4dd3-80dd-3baf768a0540)

**Comment by Stefal** [comment]
Please try to update the Mosaic-X5 to the latest firmware, and then relaunch `sudo install.sh --detect-gnss --configure-gnss`

**Comment by Jef239** [comment]
> Please try to update the Mosaic-X5 to the latest firmware, and then relaunch `sudo install.sh --detect-gnss --configure-gnss`

On  version 4.14.4 of Mosaic-X5 work normally
