### ISSUE TITLE
Lots of errors when configuring Mosaic-X5

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#422]
![image](https://github.com/user-attachments/assets/0dad0a88-30ce-4315-b68d-0be566b58f7d)

The reason is that when executing some commands, for example "`setUSBInternetAccess, on`" the response to this command comes quickly, but the execution of the next command is delayed by 17 seconds.

**Comment by Stefal** [comment]
I know, that's why I've added a retry. On your screenshot, it ended successfully, right ?

**Comment by Jef239** [comment]
> I know, that's why I've added a retry. On your screenshot, it ended successfully, right ?
YES!!!!!!
