### ISSUE TITLE
Does this work in a Debian VM?

### ISSUE THREAD

**Issue by chazzawalla** [Stefal/rtkbase#429]
Would like to install this in a Proxmox VM, probably running Debian, on an old server. I know there can be issues installing Pi software due to ARM vs x86 but thats a bit over my head.

If I set up a Debian VM and install via the script, should I expect issues? Any general advice/recommendations? Would like to move away from the Pi and run this out of my server rack.

**Comment by Stefal** [comment]
It should work.
