### ISSUE TITLE
FR: View cpu temp

### ISSUE THREAD

**Issue by Stefal** [Stefal/rtkbase#44]
View cpu temperature in settings page.

example:
```python
with open('/sys/class/thermal/thermal_zone0/temp', 'r') as ftemp:
    current_temp = int(ftemp.read()) / 1000
    print(current_temp)
```

**Comment by kikislater** [comment]
PiHole have other indicator like cpu load and memory usage. Could be nice to get inspiration 

https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L201-L208

**Comment by SPail28** [comment]
Replace 'int' with 'float' to have decimal.
Add 'current_temp = round(current_temp,2)' to have 2 décimal.
