### ISSUE TITLE
One Apply button at "GNSS Receiver detection/configuration", but you can't click on it.

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#441]
**Describe the bug**
One Apply button at "GNSS Receiver detection/configuration", but you can't click on it.

**To Reproduce**
1. Disconnect the receiver from the Raspberry Pi.
2. Start configuration.
3. Start detection.
4. See only one disabled button

**Expected behavior**

**Software/Hardware (please complete the following information):**
 - RTKBase release number 2.6.2

**Screenshots**

![image](https://github.com/user-attachments/assets/143b0635-f14c-44db-8075-f671723a5348)

**Additional context**
detectCancelBtnElt.remove(); at  $('#configure_receiver_button').on("click", function () in settings.js

**Comment by Jef239** [comment]
[commit-06225e7.txt](https://github.com/user-attachments/files/17527074/commit-06225e7.txt)

Patch for fix

**Comment by Stefal** [comment]
thanks for the bug report and the patch
