### ISSUE TITLE
Check if there is some content after __ARCHIVE__ marker (more than 100 lines) - DON'T WORK

### ISSUE THREAD

**Issue by Jef239** [Stefal/rtkbase#443]
In install_rtkbase_bundled in tools/install.sh writed

`    [[ $(sed -n '/__ARCHIVE__/,$p' "${0}" | wc -l) -lt 100 ]] && echo "RTKBASE isn't bundled inside install.sh. Please choose another source" && exit 1  
`
It doesn't work unless you put ^ in front of __ARCHIVE__ because it finds the line

`    # Find __ARCHIVE__ marker, read archive content and decompress it
`

**Comment by Stefal** [comment]
Thanks !
