### ISSUE TITLE
Is rtkbase compatible with a um980 chip rather than a f9p?

### ISSUE THREAD

**Issue by carkah** [Stefal/rtkbase#446]
Not exactly a feature request, but not a problem either.  Found a good deal on an um980 and I am just wondering if it can reaplce the f9p directly and if so what settings or setup needs to be changed

**Comment by krisgry** [comment]
You could check out [this fork](https://github.com/GNSSOEM/ELT_RTKBase/). Based on RTKbase, but supports um98X (I have not looked into what was changed to allow that)
