### ISSUE TITLE
End of update

### ISSUE THREAD

**Issue by jancelin** [Stefal/rtkbase#46]
know when the update is finished

![image](https://user-images.githubusercontent.com/6421175/82886193-79e80f80-9f46-11ea-8113-c88c272e1228.png)

**Comment by Stefal** [comment]
I think it's not possible. An update restart the web server so the connexion is lost.
But i could add a hard-coded countdown and force a refresh.

**Comment by Stefal** [comment]
I should read this in details, it could help: https://github.com/socketio/socket.io/issues/2476

**Comment by Stefal** [comment]
Contrary to what I was thinking, after a rtkbase reboot, the client (firefox in my case) seems to receive the informations from the socket. So I should be able to add some code to refresh the page.
