### ISSUE TITLE
can't modify str2str output intervals

### ISSUE THREAD

**Issue by jancelin** [Stefal/rtkbase#53]
I can't modify str2str rtcm message with output intervals

![image](https://user-images.githubusercontent.com/6421175/83348776-de80e100-a32f-11ea-8fed-b22f80358394.png)

**Comment by Stefal** [comment]
Fixed with https://github.com/Stefal/rtkbase/commit/a9140d42f46b57ea524a9bf33399edecc9377238
That's not perfect but I didn't find the correct regex pattern to refuse things like `1005()`
