### ISSUE TITLE
add a pin with Base coordinates  on map

### ISSUE THREAD

**Issue by jancelin** [Stefal/rtkbase#71]
add a pin with Base coordinates  on map

**Comment by Stefal** [comment]
I have this feature in mind since a few weeks. I search a good icon to the real location, something like a target?

**Comment by Stefal** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/8255984/84946668-58171e00-b0e9-11ea-8ff0-35472c1ab044.png)
Perhaps a larger crosshair?

**Comment by Stefal** [comment]
Feature added in https://github.com/Stefal/rtkbase/commit/fff08bbc158d063489a00a4afe2b5b0b8b3f6362

**Comment by jancelin** [comment]
![image](https://user-images.githubusercontent.com/6421175/85139274-77768e00-b244-11ea-8ece-4efb9a7b2a1b.png)
it's possible to put basertk icon on top of the other?

**Comment by Stefal** [comment]
Yes, it's possible, but the rendering is....strange:
![image](https://user-images.githubusercontent.com/8255984/85142042-105ad880-b248-11ea-9736-0fa9ee762f4a.png)

**Comment by Stefal** [comment]
With a bigger crosshair (24x24 px)?
![image](https://user-images.githubusercontent.com/8255984/85142280-64fe5380-b248-11ea-911b-5e3ca4211321.png)

**Comment by Stefal** [comment]
Crosshair extended to 24x24: https://github.com/Stefal/rtkbase/commit/d017e366e1ce5e06e4bfd357a4a58a3186c4627f
