### ISSUE TITLE
installation failed on ubuntu x86 machine

### ISSUE THREAD

**Issue by iceberg1369** [Stefal/rtkbase#81]
ERROR: pystemd-0.8.1590398158-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform

**Comment by Stefal** [comment]
Yes, I aware of this.

RTKBase need a Pystemd prerelease. I had to build the wheel for arm platform. Obviously , it fails to install on x86 platform, and then the script exit.
You can continue the RTKBase installation with:
`sudo ./install.sh --unit-files --gpsd-chrony --detect-usb-gnss --configure-gnss --start-services`

**Comment by Stefal** [comment]
Could we close this issue?

**Comment by iceberg1369** [comment]
@iceberg1369 yea. Of course
